version: 2
jobs:
  build:
    working_directory: /go/src/helm.sh/helm
    parallelism: 3
    docker:
      - image: circleci/golang:1.12
    environment:
      - PROJECT_NAME: "kubernetes-helm"
      - GOCACHE: "/tmp/go/cache"
    steps:
      - checkout
      - restore_cache:
          key: gomod-{{ checksum "go.sum" }}
      - run:
          name: install dependencies
          command: .circleci/bootstrap.sh
      - save_cache:
          key: gomod-{{ checksum "go.sum" }}
          paths: [/go/pkg/mod/cache]
      - restore_cache:
          key: build-cache-{{ .Environment.CIRCLE_PREVIOUS_BUILD_NUM }}
      - run:
          name: test
          command: .circleci/test.sh
      - save_cache:
          key: build-cache-{{ .Environment.CIRCLE_BUILD_NUM }}
          paths: [/tmp/go/cache]
      - deploy:
          name: deploy
          command: .circleci/deploy.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
